# Generated by Django 4.2.5 on 2023-12-01 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resin_apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='items',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Items'},
        ),
    ]
