# Generated by Django 5.2 on 2025-11-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resin_apps', '0005_homehero'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('promotional', 'Promotional Banner'), ('testimonial', 'Testimonial'), ('newsletter', 'Newsletter')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.TextField(blank=True)),
                ('content', models.TextField(blank=True, help_text='Additional content or description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='sections/')),
                ('cta_text', models.CharField(blank=True, max_length=100)),
                ('cta_url', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Homepage Section',
                'verbose_name_plural': 'Homepage Sections',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('rating', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('quote', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['display_order', 'name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='homehero',
            options={'ordering': ['display_order', '-updated_at'], 'verbose_name': 'Homepage Hero', 'verbose_name_plural': 'Homepage Heroes'},
        ),
        migrations.AlterModelOptions(
            name='items',
            options={'ordering': ['display_order', '-created_at'], 'verbose_name_plural': 'Items'},
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, help_text='Description for homepage collections section'),
        ),
        migrations.AddField(
            model_name='category',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Order in which categories appear (lower numbers first)'),
        ),
        migrations.AddField(
            model_name='category',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Optional: Custom image for homepage display', null=True, upload_to='categories/'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show in homepage collections section'),
        ),
        migrations.AddField(
            model_name='homehero',
            name='cta2_text',
            field=models.CharField(blank=True, help_text="Second button text (e.g., '5% OFF')", max_length=100),
        ),
        migrations.AddField(
            model_name='homehero',
            name='cta2_url',
            field=models.CharField(blank=True, help_text='Second button URL', max_length=255),
        ),
        migrations.AddField(
            model_name='homehero',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='If multiple heroes, lower numbers appear first'),
        ),
        migrations.AddField(
            model_name='items',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Order in product listings (lower numbers first)'),
        ),
        migrations.AddField(
            model_name='items',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show in featured/collection section'),
        ),
        migrations.AddField(
            model_name='items',
            name='is_latest_arrival',
            field=models.BooleanField(default=False, help_text='Show in Latest Arrivals section'),
        ),
        migrations.AddField(
            model_name='items',
            name='is_on_sale',
            field=models.BooleanField(default=False, help_text='Show in Sale tab'),
        ),
        migrations.AddField(
            model_name='items',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='If set, item will appear in Sale section', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='homehero',
            name='cta_text',
            field=models.CharField(blank=True, help_text="First button text (e.g., 'SHOP NOW')", max_length=100),
        ),
        migrations.AlterField(
            model_name='homehero',
            name='cta_url',
            field=models.CharField(blank=True, help_text='First button URL', max_length=255),
        ),
    ]
