# Generated by Django 5.2 on 2025-11-06 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resin_apps', '0006_homepagesection_testimonial_alter_category_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_type', models.CharField(choices=[('paystack', 'Paystack'), ('stripe', 'Stripe'), ('bank_deposit', 'Bank Deposit')], max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Show this payment method in checkout')),
                ('display_name', models.CharField(help_text='Display name for this payment method', max_length=100)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which methods appear (lower numbers first)')),
                ('api_key_public', models.CharField(blank=True, help_text='Public API key (e.g., Paystack public key, Stripe publishable key)', max_length=255)),
                ('api_key_secret', models.CharField(blank=True, help_text='Secret API key (keep secure!)', max_length=255)),
                ('bank_name', models.CharField(blank=True, help_text='Bank name for bank deposit', max_length=200)),
                ('account_name', models.CharField(blank=True, help_text='Account name for bank deposit', max_length=200)),
                ('account_number', models.CharField(blank=True, help_text='Account number for bank deposit', max_length=50)),
                ('bank_instructions', models.TextField(blank=True, help_text='Instructions for bank deposit payment')),
                ('description', models.TextField(blank=True, help_text='Description shown to customers')),
                ('icon_url', models.URLField(blank=True, help_text='URL to payment method icon/logo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
                'ordering': ['display_order', 'method_type'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(help_text='Unique order number', max_length=50, unique=True)),
                ('guest_email', models.EmailField(blank=True, help_text='Email for guest orders', max_length=254)),
                ('guest_phone', models.CharField(blank=True, help_text='Phone for guest orders', max_length=30)),
                ('contact_email_phone', models.CharField(max_length=255)),
                ('email_news', models.BooleanField(default=False)),
                ('delivery_first_name', models.CharField(blank=True, max_length=100)),
                ('delivery_last_name', models.CharField(max_length=100)),
                ('delivery_address', models.CharField(max_length=255)),
                ('delivery_city', models.CharField(max_length=100)),
                ('delivery_state', models.CharField(max_length=100)),
                ('delivery_postal_code', models.CharField(blank=True, max_length=20)),
                ('delivery_country', models.CharField(max_length=100)),
                ('delivery_phone', models.CharField(max_length=30)),
                ('billing_same_as_shipping', models.BooleanField(default=True)),
                ('billing_first_name', models.CharField(blank=True, max_length=100)),
                ('billing_last_name', models.CharField(blank=True, max_length=100)),
                ('billing_address', models.CharField(blank=True, max_length=255)),
                ('billing_city', models.CharField(blank=True, max_length=100)),
                ('billing_state', models.CharField(blank=True, max_length=100)),
                ('billing_postal_code', models.CharField(blank=True, max_length=20)),
                ('billing_country', models.CharField(blank=True, max_length=100)),
                ('billing_phone', models.CharField(blank=True, max_length=30)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('payment_transaction_id', models.CharField(blank=True, help_text='Transaction ID from payment gateway', max_length=255)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about the order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('payment_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='resin_apps.paymentmethod')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(help_text='Store item name at time of order', max_length=200)),
                ('item_price', models.DecimalField(decimal_places=2, help_text='Price at time of order', max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='item_price * quantity', max_digits=10)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='resin_apps.items')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='resin_apps.order')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
            },
        ),
    ]
