# Generated by Django 5.2 on 2025-11-06 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resin_apps', '0007_paymentmethod_order_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Discount code (e.g., 'SAVE10')", max_length=50, unique=True)),
                ('description', models.CharField(blank=True, help_text='Description shown to customers', max_length=200)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Discount amount (percentage or fixed)', max_digits=10)),
                ('minimum_order_total', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum order total required', max_digits=10, null=True)),
                ('maximum_discount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum discount amount (for percentage discounts)', max_digits=10, null=True)),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='Total number of times this code can be used (leave blank for unlimited)', null=True)),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='Number of times this code has been used')),
                ('per_user_limit', models.PositiveIntegerField(default=1, help_text='Number of times a single user can use this code')),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField(blank=True, help_text='Code valid from this date (leave blank for no start date)', null=True)),
                ('valid_until', models.DateTimeField(blank=True, help_text='Code valid until this date (leave blank for no expiry)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Discount Code',
                'verbose_name_plural': 'Discount Codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Shipping method name (e.g., 'Standard Shipping', 'Express')", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description shown to customers')),
                ('is_active', models.BooleanField(default=True, help_text='Show this shipping method in checkout')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which methods appear (lower numbers first)')),
                ('base_cost', models.DecimalField(decimal_places=2, default=0, help_text='Base shipping cost', max_digits=10)),
                ('free_shipping_threshold', models.DecimalField(blank=True, decimal_places=2, help_text='Order total threshold for free shipping (leave blank if not applicable)', max_digits=10, null=True)),
                ('cost_per_item', models.DecimalField(decimal_places=2, default=0, help_text='Additional cost per item', max_digits=10)),
                ('estimated_days_min', models.PositiveIntegerField(default=3, help_text='Minimum estimated delivery days')),
                ('estimated_days_max', models.PositiveIntegerField(default=7, help_text='Maximum estimated delivery days')),
                ('available_countries', models.TextField(blank=True, help_text='Comma-separated list of country codes (leave blank for all countries)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shipping Method',
                'verbose_name_plural': 'Shipping Methods',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TaxConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(help_text='Country name or code', max_length=100)),
                ('state', models.CharField(blank=True, help_text='State/province (leave blank for country-wide rate)', max_length=100)),
                ('tax_rate', models.DecimalField(decimal_places=4, help_text='Tax rate as decimal (e.g., 0.075 for 7.5%)', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tax Configuration',
                'verbose_name_plural': 'Tax Configurations',
                'ordering': ['country', 'state', 'display_order'],
                'unique_together': {('country', 'state')},
            },
        ),
    ]
