# Generated by Django 5.2 on 2025-11-06 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resin_apps', '0008_discountcode_shippingmethod_taxconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_code',
            field=models.ForeignKey(blank=True, help_text='Discount code used for this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='resin_apps.discountcode'),
        ),
    ]
